version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # Always uses the latest available Node.js version
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build # Builds the React app
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*' # Include all files in the build output directory
  base-directory: build # React's default build output folder
  discard-paths: no
